# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'
        cache-dependency-path: "**/*.sum"
        
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Send result to Discord
      if: always()
      run: |
        if [ "$GITHUB_RUN_ATTEMPT" == "1" ]; then
          STATUS="✅ Passed"
        else
          STATUS="❌ Failed"
        fi

        if [ "${{ job.status }}" == "success" ]; then
          STATUS="✅ Passed"
        else
          STATUS="❌ Failed"
        fi

        curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"GitHub Actions CI result for **${{ github.repository }}** on branch \`${{ github.ref_name }}\`: **$STATUS**\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
